### ISSUE TITLE
ForgeMultipart version downloaded by latest CodeChickenCore too outdated

### ISSUE THREAD

**Issue by apotheoseGrifter** [Victorious3/Integrated-Circuits#101]
The latest version of CodeChickenCore seems to auto-download a version of ForgeMultipart that's just one version out of date for the latest build of Integrated Circuits. This is a minor issue, of course, since I can find the latest ForgeMultipart and install it manually, but it was a bit confusing until I looked at the numbers more closely.

**Comment by Victorious3** [comment]
What's happening if you use the older version?

**Comment by Achati** [comment]
nothing.. the newer version is required.. remember the @SIdedOnly bug that was fixed in that version? maybe because you arent usiing javassist anymore we could try to revert it..
but i dont expect it to work serverside

**Comment by apotheoseGrifter** [comment]
It just tells me that it needs a version one number above, with the normal screen you get if you don't have the right prerequisites. CodeChickenCore automatically gets 331, but Integrated Circuits wants 332. Currently I have 344 and it's working like a charm so far.

**Comment by Victorious3** [comment]
This probably fixed itself by now.
