### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by Victorious3** [Victorious3/Integrated-Circuits#103]
According to this screenshot, it's long overdue: ![](http://puu.sh/ieDg9/4d49148c46.png)

**Comment by Victorious3** [comment]
I'd like to mention @Adaptivity and @Mexahoid here, I know that you two have done the one for BetterStorage, so what about this one?

**Comment by Mexahoid** [comment]
You need a translation?

**Comment by Victorious3** [comment]
@Mexahoid Yep, would be awesome!
