### ISSUE TITLE
0.9 Project:Red FMP connectivity issues

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#106]
FMP build 1.2.0.344 (and 345 too).
Project:Red build 4.6.2.82 (latest).

In general, single wires only refuse connecting over edges, and bundled cables refuse connecting at all. Your 7-segment displays do, however, connect properly (while P:R ones do not).
When I say "don't connect" I mean at all, not just visually.

Screenshots:
![screenshot from 2015-06-08 22 39 19](https://cloud.githubusercontent.com/assets/6692701/8044028/8d957bb2-0e32-11e5-8c7e-57657f958f75.png)
![screenshot from 2015-06-08 22 41 32](https://cloud.githubusercontent.com/assets/6692701/8044045/a26dd64c-0e32-11e5-8489-6fc17d43fa54.png)
![screenshot from 2015-06-08 22 45 27](https://cloud.githubusercontent.com/assets/6692701/8044058/bb2e0b3e-0e32-11e5-82ea-db7b5bac1df6.png)
![screenshot from 2015-06-08 23 31 15](https://cloud.githubusercontent.com/assets/6692701/8044614/82ca25d0-0e36-11e5-84f5-68da01c65c05.png)

Also, FMP socket interacts with RedLogic wires the same way. (Although, obviously, you can not place them in the same block as they are not FMP.)

The non-FMP socket is fine. (It does not connect over edges, but I guess it is intended).

------

As a side note, 0.8 worked ~~"~~fine~~"~~ within the same setup.
I tried 0.9 because ~~in 0.8 FMP gates *ignored bundled input changes*, while output and non-FMP gates were fine~~ I must have been crazy. (Things like state cell and rs latch were broken ~~too~~, but it was not critical and I don't know if they are fixed).

**Comment by evg-zhabotinsky** [comment]
I have tried to understand how it works, and it looks like GPProjectRedFMP.connect* methods are never called! I do not know why.

**Comment by Victorious3** [comment]
@evg-zhabotinsky The cells weren't changed since 0.8, what's wrong with them exactly?

**Comment by evg-zhabotinsky** [comment]
@Victorious3 I found it.
Basically the same problem as in #107, but in this case nothing crashed:
```
diff --git a/src/main/java/moe/nightfall/vic/integratedcircuits/api/IntegratedCircuitsAPI.java b/src/main/java/moe/nightfall/vic/integratedcircuits/api/IntegratedCircuitsAPI.java
index 6af310b..ab3f9a3 100644
--- a/src/main/java/moe/nightfall/vic/integratedcircuits/api/IntegratedCircuitsAPI.java
+++ b/src/main/java/moe/nightfall/vic/integratedcircuits/api/IntegratedCircuitsAPI.java
@@ -17,7 +17,7 @@ public class IntegratedCircuitsAPI {
 
 	public static enum Type {
 		TILE("moe.nightfall.vic.integratedcircuits.tile.TileEntitySocket"),
-		TILE_FMP("moe.nightfall.vic.integratedcircuits.tile.FMPartGate"),
+		TILE_FMP("moe.nightfall.vic.integratedcircuits.tile.FMPartSocket"),
 		BLOCK("moe.nightfall.vic.integratedcircuits.tile.BlockSocket");
 
 		public final String classname;
```
