### ISSUE TITLE
Caught exception from integratedcircuits

### ISSUE THREAD

**Issue by Tsyklop** [Victorious3/Integrated-Circuits#107]
Crash. http://pastebin.com/MhUXj87t . Forge 1445 1.7.10. integratedcircuits-1.7.10-0.9r34.171

**Comment by skyem123** [comment]
Ah. I know what caused that. It was fixed in 60665fc6300c6df1ae3246c98ee05d79bcd4bd00, but that's on the dev branch, so I made the equivalent fix on the master branch.

**Comment by skyem123** [comment]
The latest Jenkins build should be working now.

**Comment by Tsyklop** [comment]
thx
