### ISSUE TITLE
Misbehaving gates.

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#108]
Tested in 0.8, both in CAD and in finished IC.

**State cell**
If you turn the bottom input (as per default orientation in CAD) off and then back on while gate is still counting and right input is off, the bottom input will no longer stop countdown.
This glitch persists when gate is deactivated and reactivated.
Turning on the right input fixes it. (Until you do the same thing again.)

**Transparent latch**
When its bottom input is off, it should ignore left input and keep outputs the same.
When bottom input is on, it should pass left input to outputs as is.

So, when you turn bottom on, then left on, then bottom off and then left off, outputs stay on.
If you turn bottom on after that, it *should* turn outputs off immediately.
Instead of that, it turns outputs off only when you turn bottom off again, or toggle left on and off.

**RS latch**
Not sure about that, but I think I've seen it being stuck with all outputs off after turning both inputs on and off simultaneously. Maybe it was glitch with wires (see #109), I can't reproduce it now.
Anyway, its image in CAD does not reflect its state and mode.

**Comment by Achati** [comment]
0.8 is incomplete.. could you test that on 0.9 please?
the newest jenkins build should be reasonably stable

**Comment by evg-zhabotinsky** [comment]
@Victorious3 said that gates didn't change since 0.8.
Yesterday the latest jenkins build was just crashing and I didn't want to setup build environment again (I built it on another machine yesterday).
Will test on 0.9 now.
