### ISSUE TITLE
Add "Disabled" IO port mode.

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#110]
Just like Bundled/Analog/Simple.
There corresponding side of IC should have no wires at all and should not connect to anything.

This sounds as a really simple addition.
You already can leave one side unconnected, achieving roughly the same result, but IMHO disabling the side is better.

**Comment by Victorious3** [comment]
Right, shouldn't be too hard to pull off... Been postponing it forever because nobody seemed to be interested and as you already mentioned, ignoring the output works. However, it gives the impression of functionality on that  side, not an ideal solution... I'll get to it.

**Comment by skyem123** [comment]
@Victorious3, "I'll get to it", and, a few months later, you haven't done anything? :stuck_out_tongue:

Do you want me to try to implement this, or do you want to do it yourself?

**Comment by skyem123** [comment]
@Victorious3, I starting trying to implement this, but I ended up walking into network code...

**Comment by skyem123** [comment]
Huh, interesting, there already is a `None` in `EnumConnectionType`...

**Comment by skyem123** [comment]
@Victorious3! Why is your code so cryptic?!

**Comment by skyem123** [comment]
Oh, phew, it seems to have room for the none mode.
