### ISSUE TITLE
Integrated Circuits 0.9r34.173 outdated Computercraft API?

### ISSUE THREAD

**Issue by Xiaminou** [Victorious3/Integrated-Circuits#117]
Original Post : https://github.com/OpenMods/OpenPeripheral/issues/248

Updating Integrated Circuits from 0.8r34b to 0.9r34.173 crashed my entire ComputerCraft network.
Rolling back to 0.8r34b fixed the problem.
Please read the Original Post if you want additional Informations.

**Comment by boq** [comment]
Just to clarify: version of CC API bundled with your mod is outdated.

Please don't bundle APIs. Proper way to do that is to put API files in `/src/api/java` - they will be visible during build, but not added to release jar.

**Comment by Victorious3** [comment]
@boq The API files are used along with OC for shared code, I have to rewrite it first to allow for that, i.e using my own interfaces.

**Comment by boq** [comment]
Hmm?

You already have properly marked everything with `cpw.mods.fml.common.Optional` annotations. Everything should be fine with just few 'ifs'.

Java tries to load classes as late as possible: it will crash only when you try to load missing class, either via referencing field of that type, calling method with such parameter or executing line that references that class. Loading class that just contains references is safe.
