### ISSUE TITLE
Phantom input updates

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#122]
After c0df9476c1e4aab09c95a1e581e565277df058d2, gates started to receive phantom input updates.

Example:
Connect 2 I/O pins with wire, and hook this wire to a toggle latch.
Turn first pin on, then second on, then first off.
When turning first pin off, wire will remain on (because second pin is also driving it), but toggle latch will toggle.

Actually, gates now receive **many** input updates (i.e. `onInputChange` calls) per tick, usually with different values, and it breaks some gates, like pulse former and toggle latch.

Just putting a buffer gate between that flickering wire and faulty gate fixes the problem for now, at  a cost of extra tick and PCB space.

**Comment by Victorious3** [comment]
Well, now its completely broken. Starting to think about giving up on the concept of giving the gates the side of the input change...

**Comment by ljfa-ag** [comment]
I think the only way to avoid problems like these is treating the wires as a graph and finding out connected components in them.

**Comment by evg-zhabotinsky** [comment]
Not too complex though.
You can propagate "net updates" on circuit edits (which will treat wires and wire-like parts of other gates alike), during which gates will also register as their listeners and signal providers for specific nets, and then synchronously tick the whole circuity.

**Comment by Victorious3** [comment]
Well, looking at this my current system works, its just that gates update in the same tick they are notified. If I cause the change to happen in the tick after, drop the input change per side and instead call it only once, that should do the trick.

**Comment by evg-zhabotinsky** [comment]
Have just been writing that!

In fact, only toggle latch, pulse former, synchronizer and repeater are affected.
Randomizer is also affected, but it is quite random anyway :-)

The signal only erroneously flickers from high to low (and finally ends up high) and not the other way around, so the transparent latch, timer and state cell are not affected.
Simple logic is already synchronous (because of single tick delay).

**Comment by evg-zhabotinsky** [comment]
I have thought on that for a bit.

Some gates (like buffer cell) **do** require instantaneous signal propagation and consequently must receive input updates immediately.
So you will either **add** separate ticked version of input update handler, or leave it up to the gate to tick itself.

The latter variant, considering that only 4 gates are broken, is quite easy.
And it will just remove "input actually was changed" meaning from `onInputChange` handler.

**Comment by evg-zhabotinsky** [comment]
Should be fixed by #125
