### ISSUE TITLE
Zero tick signal pulses are ignored within IC but show up on outputs.

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#135]
These 0-tick pulses happen when e.g. wire is driven high by several gates and one that was turned on first finally turns off.
Gates inside circuit (e.g. toggle latch) ignore these, but if that wire is connected to IO pin, these 0-tick pulses get outside.
In case of P:R, they are ignored by most gates, but switch RS and toggle latches for example.

Need to understand how it works and rewrite `PartIOBit` and related code.

**Comment by evg-zhabotinsky** [comment]
As I understand, it is impossible to check if IO pin is powered from outside if it is powered from inside.

Consider following configuration: IO pins A and B and output of a buffer gate are connected inside IC.

Initially, everything is turned off.
Buffer gate drives their common wire high and both IO pins start outputting signal.
Then pin A gets powered from outside (IC does not "know" about it).
Finally, buffer gate turns off, and their common wire goes low (because IO pins are working as outputs now).

Now, we have to turn off one of IO pins to find out if it is powered from outside.
We can't guess anything, so suppose we turned off B first.
B is not powered from outside, so wire is still low, and now we have to check A.
We turn A off, it is powered from outside so it starts powering the common wire.
This turns B on again.

In the above scenario, output B will pulse low no matter what. It is impossible to "fix" it without touching P:R.

**IMO:** It is counterintuitive if the wire connecting IO pins will not pulse in this case, because it is the only thing that drives output B and that output will pulse. By design, zero-tick pulses are not considered to be pulses inside IC, so both that common wire and output B should be turned off for a whole tick.

Because of what I explained above, I made IO work synchronously in #143

**Comment by Victorious3** [comment]
0 tick pulses can be avoided by another synchronization step between circuit and the outside. Right now the output is stored in the IO pins because it is more cheaper to do it that way. Instead, I could do it like the the CAD does and store it individually (as a byte array), and thus degrading the IO bits to a relay.

**Comment by evg-zhabotinsky** [comment]
> 0 tick pulses can be avoided by another synchronization step between circuit and the outside.

Er... No. Maybe I did not explain it well enough. Problem is not with synchronization. I can easily fix escaping 0-tick pulses that are caused by internal components only, but not all of them are.

The problem actually arises when 2 or more IO pins are directly connected with wire inside integrated circuit. Such IC acts as a bidirectional repeater (or 3-way repeater, or more), not as a wire piece. 
And with such symmetrical repeater, *all the outputs will (at least momentarily) go low when the "driving" input changes*.
You can do nothing about it.
And if at least 3 IO pins are connected with wire, this will cause at least one of them to momentarily go low, and "for no apparent reason" if it is a 0-tick pulse, as they cannot be detected inside IC.

In #143, I just made internal IC behavior consistent with "inevitable" external behavior described above, by making these pulses last for the whole tick.

**However**, everything described above only holds in case *when it is not possible to actually read input when output is high*, as it is hardcoded right now: input is always reported low when output is high (except in CAD).

So this issue might better be left alone until someone implements *"Are there any other power sources connected to this wire, besides this IC?"* kind of functionality.

**Right now**, I am only able to eliminate *most* of escaping 0-tick pulses, not all of them.
More precisely, 0-tick pulses will never show up on IO pins that are not connected directly to other IO pins.

**Comment by evg-zhabotinsky** [comment]
Hmm... I did not think about it before, but...
Maybe it is fault on P:R side?
Really, most P:R gates and vanilla redstone ignore even 1-tick input pulses, and all ignore 0-tick pulses.
Currently, exceptions are toggle latch and pulse former and maybe couple other gates.

**Comment by evg-zhabotinsky** [comment]
Hmm. Chicken-Bones said that they will fix their ICs to update outputs with 2-tick delay.
If we go the same way, I did exactly that in #143.

Otherwise, well, I don't know yet.
Maybe they will make their gates ignore 0-tick pulses, and then I will just remove unnecessary ones. Vanilla, RedLogic and MFR all seem to ignore 0-tick pulses, although I am not sure if it will stay this way forever.

**Comment by evg-zhabotinsky** [comment]
Ahh well, me stupid.
If signal strength is *not* propagated through IC, wire loops passing through IC *will self-power*.
And if outputs are *not* updated synchronously (i.e. no more than once a tick), it will happen unreliably and "for no apparent reason".
So making outputs update synchronously (#143) is what should be done IMO.
