### ISSUE TITLE
Client crash (during BTM15 convention)

### ISSUE THREAD

**Issue by maruohon** [Victorious3/Integrated-Circuits#138]
I had been on the server something like 15 minutes already, suddenly the game crashed with the following crash report: http://pastebin.com/uFkMeDVU

**Comment by evg-zhabotinsky** [comment]
From Google results, it seems to be a very common issue and disabling RailCraft's heat system "fixes" the problem.
[This](https://github.com/CoFH/Feedback/issues/1) (referring to [this code](https://github.com/CoFH/CoFHCore/blob/387af4b1a28708dec48fb681ed0517079c9c89bf/src/main/java/cofh/core/block/BlockCoFHBase.java#L87-L101)) says that it is actually Mojang's fault and seems to present a fix. I didn't quite understand if it can happen in other cases, but in this case just return `null` if not instance of proper class.

**Comment by Victorious3** [comment]
I love it if its just doing random...
