### ISSUE TITLE
Sequencer behavior change

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#140]
Some circuit parts did not work correctly, so I changed how they work in #125 (and a bit in #130).
While doing so, I changed all gates to work as in P:R.

However, I am not sure if I should have changed how sequencer works.

#### Old behavior
Waits for set delay, emits 2-tick pulse and switches to the next side (like timer).

#### New behavior
Emits high signal for set time and then switches to the next side.
**+** Works as in P:R.
**+** Old behavior can be achieved using pulse formers.

#### Changes that can break old circuits
**-** Now emits solid signal instead of pulses
**-** Total period decreased by 8 ticks (2 ticks per side, as there are no pulses now).

@Victorious3 Should any of the above 2 changes be undone?

**Comment by Victorious3** [comment]
I don't think that it makes that much of a difference. I will mention it in the changelog, but overall P:R (RedPower) behavior is preferred and should be corrected to match.
