### ISSUE TITLE
Problems with comments

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#142]
They are not finished, but just in case (at least not to forget):

* Comments are not cleared on PCB clear / resize.
* It is possible to close that "drawer" with comment tools while one of them is still selected, and then keep guessing why did that comment disappear...

**Comment by Victorious3** [comment]
First one I didn't know about but would have noticed, Second one I know about.
Thanks.

**Comment by Victorious3** [comment]
Should be resolved by now.
