### ISSUE TITLE
Screwdrivers don't work

### ISSUE THREAD

**Issue by Victorious3** [Victorious3/Integrated-Circuits#149]

**Comment by skyem123** [comment]
Note to future self: move the checking to block the screwdriver rotating to the Tile Entity used by the normal socket block to allow other types of sockets to work.

Also check if the ICs screwdriver is implementing things properly?

**Comment by skyem123** [comment]
Okay, this should be fixed, but I have one more problem.
The screwdriver from RedLogic doesn't work with a shift-right-click. This is not our fault, but it still is important so we need to contact the author of RegLogic to fix this.
