### ISSUE TITLE
drag to place rows of other components like wires

### ISSUE THREAD

**Issue by GopherAtl** [Victorious3/Integrated-Circuits#15]
It'd be convenient if other components, especially the cells, could be clicked and dragged to place rows of them, the same way you can with wires. with null cells in particular, which I find myself using more often than wires when I've been trying to compact designs down as much as possible, it'd actually be nice to drag not just a line, but a rectangle to fill with them.

**Comment by Victorious3** [comment]
A mode that allows you to fill a selection is a good idea, I could combine it with copy & paste which will also need a selection method.

**Comment by Victorious3** [comment]
Resolved by introducing the selection mode.
