### ISSUE TITLE
Sockets are uncraftable

### ISSUE THREAD

**Issue by evg-zhabotinsky** [Victorious3/Integrated-Circuits#150]
Also, FMP sockets are still broken (#106), so maybe they should not be craftable just yet.
**Edit:** I fixed #106 (see my comment on it).

**Comment by ljfa-ag** [comment]
Oh yeah, that's missing indeed

\>things you don't notice when you only test in Creative :P

**Comment by skyem123** [comment]
Should this be closed?

**Comment by ljfa-ag** [comment]
Well the recipe is there now...
