### ISSUE TITLE
pause, step through simulation in CAD program

### ISSUE THREAD

**Issue by GopherAtl** [Victorious3/Integrated-Circuits#16]
it would be quite useful at times when debugging circuit designs to be able to pause the simulation and advance it a tick at a time, to see how signals are flowing through the circuit.

**Comment by moTechPlz** [comment]
So we need; play/continue, pause/stop, step, reset

**Comment by Victorious3** [comment]
I don't really know how reset is supposed to work, the thing is, if you have a bunch of gates and set them back to their original position it will propagate a lot of signals which will cause them to change the state right after, probably at something that you don't want.

**Comment by moTechPlz** [comment]
Your right. I was thinking about selecting a gate to reset One at a time and only if applicable.

**Comment by Victorious3** [comment]
Added with a0d41a620f31fb3e4e7f0fcdf9cb6eb7f26da705
