### ISSUE TITLE
Crash while using on server

### ISSUE THREAD

**Issue by Landstryder** [Victorious3/Integrated-Circuits#168]
Here is the crash report from the server when I tried to place a segment display on a FMP plate. Got the same crash when trying to place a circuit on a FMP plate.

http://pastebin.com/cz9RQQY4

I also got a client side crash when trying to adjust the settings of the segment display (when the server came back up the display was there on the plate looking all pretty), but it was not a hard crash so no report was generated only took me back to title screen with a net error.

Server also crashed when I placed a rednet cable connecting between the circuit and segment display same basic text as above crash log I'm told by our OP (that was the point at witch it was removed from the server). It also crashed our clients with this report.

http://pastebin.com/HdumeTPe

**Comment by skyem123** [comment]
Quick question, what version / build of this mod are you using?

**Comment by Achati** [comment]
`UCHIJAAAA       integratedcircuits{1.7.10-0.9r36} [Integrated Circuits] (integratedcircuits-1.7.10-0.9r36.jar) ` does that help ?

**Comment by skyem123** [comment]
As far as I can tell, the first crash was fixed some time ago, so you are somehow using an out of date version. Can you get the latest build from the build server and see if the crashes happen again?

**Comment by skyem123** [comment]
Well... This bug has been fixed in our development builds, so you can either use a development build from the build server or poke @Victorious3 to finish up and release a new version.
