### ISSUE TITLE
bug - changing size of circuit does not always work properly?

### ISSUE THREAD

**Issue by GopherAtl** [Victorious3/Integrated-Circuits#17]
the size button on the cad gui doesn't work properly for me. Usually, from a 32x32, clicking it will update to 64x64 as expected, but clicking again doesn't appear to do anything.I say *appear*, it actually *does* something, because if I save and re-load, it redraws as the new, blank 16x16 circuit, but if I don't, it continues to display the 64x64, without even clearing the previous circuitry. Worse, making changes to the circuit while it's in this state *can* cause the game to crash. Clicking the resize button again while it is showing a 64x64 but saving a 16x16 has no effect at all; it will continue to save a blank 16x16 to disk (according to tooltip) until either I load the saved circuit from disk, or exit to the mc menu and re-load the saved game. Same behavior occurs when switching from 16x16 to 32x32.

Running this on v1.7.10, with the new launcher setup (the one that handles it's own java version).
The following are the installed mods:
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
ComputerCraft1.65.jar
Integratedcircuits1.7.10-0.8r26.jar
JourneyMap5.0.1_Unlimited_MC1.7.10.jar
NotEnoughItems-1.7.10-1.0.4.83-universal.jar
ProjectRed-1.7.10-4.5.8.59-* (all 5 sub-mods: Base,Compat,Integration,Lighting, and World)

**Comment by Victorious3** [comment]
That's weird, never noticed anything similar. I'll look into it to see weather I can reproduce it somehow. Does it happen every time or at an irregular basis?
