### ISSUE TITLE
Circuit Blueprints are horribly broken and inconvenient

### ISSUE THREAD

**Issue by Achati** [Victorious3/Integrated-Circuits#178]
after soime time printouts placed in itemframes display one section of the circuit zoomed in or just a grey background or a quarter of the board is flipped or disappears

PS: cant place those on the floor or ceiling, itemframes are maybe not the best thing to use

PPS: the same issues somrtimes happen on the assembler in-world renderer but are less noticable cause they only happen when looking at it from certain angles

will supply screenshots tomorrow..

**Comment by skyem123** [comment]
May I ask why this is closed, @Victorious3?

**Comment by ljfa-ag** [comment]
Seems like @Achati already fixed it
