### ISSUE TITLE
The New Stefinus Guns Metal Grip

### ISSUE THREAD

**Issue by Kaos1234** [Victorious3/Integrated-Circuits#181]
Upon attempting to make a metal grip for a Desert Eagle, i found that Railcraft steel ingots make 4 steel rods and i cant make the metal grip that is needed

**Comment by skyem123** [comment]
How is that related to this mod?

**Comment by Kaos1234** [comment]
I clicked on the link from the mod pack I was trying to post this In, I'm not sure why it sent me here

**Comment by skyem123** [comment]
Ah, what modpack is it from?
Also, that link was only for this mod, which is called "Integrated Circuits", which has a habit of breaking things.

I think I found the MinecraftFourms page for the mod you are talking about: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2361243-new-stefinus-3d-guns-mod. However, it looks like it hasn't been updated in almost a whole year.
