### ISSUE TITLE
Is anyone picking up this mod, vic gave link for somone to pic up

### ISSUE THREAD

**Issue by stick-shift** [Victorious3/Integrated-Circuits#184]
check the curse page in the comments section, plz someone try to port this to 1.12.2
im currenlty learning how to mod and such or id do it my self but i fear it could be a very long time and this is time i do not have, being unstable in life atm

**Comment by skyem123** [comment]
Sadly, I don't have the time to maintain a Minecraft mod and, this would take a very long time to port and is probably going to be very hard to port as well.

@Victorious3 doesn't do anything related to Minecraft anymore.

Though you're welcome to try to improve / port this mod, as long as you follow the licence.
