### ISSUE TITLE
make opposing bundled outputs match?

### ISSUE THREAD

**Issue by GopherAtl** [Victorious3/Integrated-Circuits#20]
currently the bundled outputs are rotated, so they're white to black going counter-clockwise; this ends up requiring me to use a lot of space to reverse wire orders at times that wouldn't be necessary if the top and bottom both started with white on right, and both sides with white on top. This would obviously be a breaking change for existing circuits, so if it was going to be done, it ought to be done sooner than later.

**Comment by Victorious3** [comment]
On one end you'll have to reverse the order, currently you can connect either side with the one to the left of it, they match up. However, I agree that a straight connection is probably needed in most of the cases, I'll change it. Oh, it doesn't break existing ones btw, so that's not a problem.

**Comment by GopherAtl** [comment]
if you're doing a 90 degree turn it works just as well either way; one way, they all cross and you have that angle bend like in the computercraft screenshot from the official thread, other way, just alternating red/orange wires would do it, though admittedly they'd take up a bit more space. And if tunnels are actually implemented at some point, the whole question becomes moot anyway.

**Comment by Victorious3** [comment]
I just remembered why I did this in the first place, it's because the 16x16 would intersect if they were straight.

**Comment by Victorious3** [comment]
Not really needed anymore due to tunnels.
