### ISSUE TITLE
Circuit not operating properly after chunk loads

### ISSUE THREAD

**Issue by wooky** [Victorious3/Integrated-Circuits#25]
When a circuit gets loaded after being unloaded, it does not output any redstone/bundled signal, which is bad if the input to the circuit depends on the output. Applying a simple redstone signal makes it operate properly, but I'd rather not have to do that on every world load.

**Comment by Victorious3** [comment]
Try the same setup with FMP gates and tell if those work.

**Comment by Victorious3** [comment]
Sorry for taking so long on this, I finally got to reproduce it.

**Comment by Victorious3** [comment]
Can you please verify the fix?

**Comment by wooky** [comment]
Okay, I'll verify it soon. I'd appreciate if there was a build with the fix so I don't have to build it myself.

**Comment by Victorious3** [comment]
Last one has it, 0.8r31
