### ISSUE TITLE
The Lua code in OpenComputers errors if an IC is connected to a computer without RedLogic installed.

### ISSUE THREAD

**Issue by skyem123** [Victorious3/Integrated-Circuits#30]
Someone else found this issue: MightyPirates/OpenComputers#941

**Comment by skyem123** [comment]
I want to try to fix it with Sangar's suggestion.
I'm sure @Victorious3 will be OK with me trying... (Vic is lazy!)

**Comment by Victorious3** [comment]
Sorry, too late ^^

**Comment by skyem123** [comment]
;_;
I can't program and test at school!
Meanie.
