### ISSUE TITLE
multi spawn when removing the block underneath a IC

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#32]
When you remove the block underneath an integratedCircuit, an enormous amount of IC's get spawned. 
![2015-02-26_16 19 48](https://cloud.githubusercontent.com/assets/11203133/6394895/06cc7c78-bdd5-11e4-83c2-acf912c8e28c.png)
Same thing happens again when you delete the hovering IC itself. However, if you place a block underneath it and then delete it, it removes correctly.

**Comment by Victorious3** [comment]
Gonna leave this in because it looks so neat to have all the tiny circuits floating around... No seriously... What? Shit.

**Comment by moTechPlz** [comment]
This also happens when you place a IC on the wall and remove the block behind it. Also if you place it on a ceiling and remove the block above it.
