### ISSUE TITLE
transparentLatch does not function the same as a projRed.transparentLatch

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#36]
I've made this test setup: A row of transparentLatches with a timer set to one second for the lock input. A toggleLatch to divide the frequency and hold the signal for the signal input.
![2015-02-27_13 30 29](https://cloud.githubusercontent.com/assets/11203133/6412562/da63cfcc-be85-11e4-8975-2232f3cd5a8f.png)
All latches match the input signal immediately when a clock pulse arrives on the lock input. Same schematic in projRed works like this:
![2015-02-27_13 30 13](https://cloud.githubusercontent.com/assets/11203133/6412937/622762a8-be8a-11e4-865e-0b0e281d4aaf.png)
This difference probably because of a lack of delay in the output signal. Putting a buffer in between the latches will make the IC work like the projRed setup does.
![2015-02-27_14 00 14](https://cloud.githubusercontent.com/assets/11203133/6413002/feef75b2-be8a-11e4-8a9d-76985b5a9637.png)

**Comment by Victorious3** [comment]
If you have any RS Latches laying around, they might blow up after this change.
