### ISSUE TITLE
name not displayed on disk if using the standard name NO_NAME

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#42]
when you create a circut with the CAD and save it with the standard name NO_NAME, the name is not displayed on the floppyDisk. If you insert the floppyDisk in the Assembler it does tell the circuit name is NO_NAME. Also the name is also displayed on the created IC.

**Comment by Victorious3** [comment]
Indeed. I knew of this quite a while and waited for someone to find it, better go finding the cause then,,,
