### ISSUE TITLE
redAlloy and bundled not connecting coming from an angle

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#43]
When a connection comes in from a 90 degree angle below, in the IC perspectives, they will not connect.
![2015-03-01_22 17 41](https://cloud.githubusercontent.com/assets/11203133/6432870/d8b8e112-c060-11e4-9621-fbb5377e5c96.png)
![2015-03-01_22 14 05](https://cloud.githubusercontent.com/assets/11203133/6432865/ab376d3a-c060-11e4-867d-a66696b60752.png)
Also coming from a 90 degree above angle, it does not allow placement of the wire or cable.
![2015-03-01_22 14 58](https://cloud.githubusercontent.com/assets/11203133/6432879/2ac7372e-c061-11e4-8875-27f60d20efdd.png)

**Comment by skyem123** [comment]
Try using the FMP version. Surround the IC in stone covers to craft it.

**Comment by moTechPlz** [comment]
Yes, that does work. 
![2015-03-01_23 54 06](https://cloud.githubusercontent.com/assets/11203133/6433414/94789be2-c06e-11e4-90f9-3b2f68c842ad.png)
![2015-03-01_23 54 11](https://cloud.githubusercontent.com/assets/11203133/6433415/956b7d58-c06e-11e4-9d11-1802d6db2c4e.png)

**Comment by Victorious3** [comment]
This is the problem of P:Rs API which doesn't allow edge connections for TileEntites. The second one you mentioned is impossible, the other two might be achievable by diving into the internals for a bit. Othewise, if you have P:R installed, you can simply craft the FMP version of the gates instead as @skyem123  mentioned. But be aware of the incompatibilities with the other mods, P:R is the only one being able to connect to them.

**Comment by moTechPlz** [comment]
Should i ask for edge connections for tileEntites at projRed or would this not be possible technically?

**Comment by Victorious3** [comment]
@moTechPlz Let's say that they didn't account for it. If I am lucky I can get them to work, the problem is the renderer... If the wire doesn't ask for an edge connection there is not much I can do about it, even if I get the signal nobody will know that the connection occurs.

**Comment by moTechPlz** [comment]
Hmm, got this answer; "They already connect to other parts such as gates. They can only connect around corners if the tile is specifically made that way."
https://github.com/MrTJP/ProjectRed/issues/730
I have no idea what he's talking about. :P But i noticed the bigReactor mod and openComputers mod won't connect around corners either, so no big deal.
