### ISSUE TITLE
tooltips go beneath the NEI gui

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#45]
Hi, noticed the tooltips go beneath the notEnoughItems mod gui. Makes them hard to read. 
![2015-03-02_21 09 19](https://cloud.githubusercontent.com/assets/11203133/6450344/76f7b4e0-c127-11e4-9f4d-af26af6a39a4.png)![2015-03-02_21 57 16](https://cloud.githubusercontent.com/assets/11203133/6450345/77cbafb6-c127-11e4-9e93-3fe6464142d5.png)
I'm a neeb at mineCraft modding but maybe you need to call the codechickenLib drawMultilineTip instead :/

**Comment by evg-zhabotinsky** [comment]
This is "fixed" with removal of NEI from CAD gui.

**Comment by Victorious3** [comment]
Yeah.

**Comment by evg-zhabotinsky** [comment]
My bad, I didn't pay enough attention to the second screenshot.
Required resources' tooltips still go beneath NEI.
Will take a look at it.

**Comment by evg-zhabotinsky** [comment]
@Victorious3 I think you should take a look at it.
Changing function [here](https://github.com/Victorious3/Integrated-Circuits/blob/3471f2c92916f4687f13288872962b577ddb5592/src/main/java/moe/nightfall/vic/integratedcircuits/client/gui/GuiAssembler.java#L212-L220) from `drawGuiContainerForegroundLayer(x, y)` to `drawScreen(x, y, f)` (and adding `super.drawScreen(x, y, f)` of course) seems to work fine.
I didn't notice any new visual glitches after this change, but I am absolutely not sure what `RenderHelper.enableGUIStandardItemLighting()` is for there or if any other changes are needed.

**Comment by skyem123** [comment]
@Victorious3, yeah, the error is here for the missing item thing in the assembler.
[screenshot](https://cloud.githubusercontent.com/assets/2051085/8512643/bedc5926-2344-11e5-8c7c-c5c108e8790e.png)

**Comment by evg-zhabotinsky** [comment]
Now it is actually fixed.
