### ISSUE TITLE
vertically placed IC's do not connect to projRed.alloyWire from below

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#49]
When placing an IC' vertically it does not connect to a projRed.alloyWire from below.
Same chip rotated;
![2015-03-03_23 51 57](https://cloud.githubusercontent.com/assets/11203133/6474443/106118f4-c201-11e4-971e-cac730307230.png)![2015-03-03_23 53 52](https://cloud.githubusercontent.com/assets/11203133/6474445/118b1b44-c201-11e4-88c7-7aa9ee1a4739.png)![2015-03-03_23 53 59](https://cloud.githubusercontent.com/assets/11203133/6474449/12b0ceb0-c201-11e4-89f4-c7c123f17679.png)

Floor and ceiling placed IC's work correct, so does bundled cable connections.

**Comment by Victorious3** [comment]
This is a bug with P:R again, it doesn't ask if a connection from the bottom side is possible. It might only be a rendering related thing and it actually propagates the signal, if you are lucky in both directions, if not, only from the circuit to the wire.

**Comment by moTechPlz** [comment]
Ok, i can confirm they do not propagate the signal. I'm not going to ask for this one at projRed, given the easy answer of my last request. Good thing you have the FMP versions to deal with projRed. Hope bluePower will be of better quality when they actually finish it.
