### ISSUE TITLE
analog output signal has priority over input signal even when of lower strength

### ISSUE THREAD

**Issue by moTechPlz** [Victorious3/Integrated-Circuits#50]
I've made a test circuit like so; 
![2015-03-04_18 28 13](https://cloud.githubusercontent.com/assets/11203133/6489245/251f0980-c29d-11e4-9bcf-28ea3d6c0c80.png)
I put a torch giving a strength 15 signal on the analog side.
![2015-03-04_18 13 03](https://cloud.githubusercontent.com/assets/11203133/6489342/e5bfcfda-c29d-11e4-820a-8c18b1e2f17e.png)
If i then input a signal on the right simple IO connected to the strength 14 output of the analog IO. The strength 15 input will no longer give a signal to the left simple IO.
![2015-03-04_18 12 58](https://cloud.githubusercontent.com/assets/11203133/6489322/cc4eb462-c29d-11e4-9372-773b1a9d52ff.png)

**Comment by Victorious3** [comment]
Hmm. Looks like something that I didn't consider, I'll have a look.

**Comment by Victorious3** [comment]
Fixed in 0.9
