### ISSUE TITLE
Stupid Newbie Assistance (or: where's the manual so I can RTFM)

### ISSUE THREAD

**Issue by Techokami** [Victorious3/Integrated-Circuits#51]
Yeah, I'm having some difficulty figuring out how to work the GUI in the CAD, depressingly. It took me a few weeks to figure out that you can pan the view with Shift + Left Mouse! But uh, how do I insert a disk into the CAD? I tried shift-clicking the disk on the block but that didn't work...

**Comment by moTechPlz** [comment]
Equip the disk use it (right-click) on the black slot at the bottom of the device.
![2015-03-04_19 35 04](https://cloud.githubusercontent.com/assets/11203133/6490349/e2fbb89c-c2a5-11e4-9fd9-e3c6e6085085.png)
Here the left Assembler has a disk named CNT-TST in it.

**Comment by Techokami** [comment]
Wow, I did not know that. There needs to be some sort of a manual, or at least some sort of usage documentation on [the wiki](https://github.com/Victorious3/Integrated-Circuits/wiki) GitHub provides projects.

**Comment by moTechPlz** [comment]
Well this is mod is still in Alpha, the documentation can wait for now since things are still open for change.

**Comment by Victorious3** [comment]
![How To](http://giant.gfycat.com/DimwittedChiefGoldeneye.gif)

**Comment by skyem123** [comment]
Why not add a "lore text" to the blueprint disk that explains what to do with it?

**Comment by Victorious3** [comment]
Well, I *assumed* this was like the second thing people would try...

**Comment by skyem123** [comment]
You *assumed*? That is a bad idea. Very. Bad.
/me slaps @Victorious3

**Comment by Victorious3** [comment]
They are just not creative enough!

**Comment by skyem123** [comment]
.-.
