### ISSUE TITLE
Additional Features 0.9 

### ISSUE THREAD

**Issue by Victorious3** [Victorious3/Integrated-Circuits#57]
- [x] Refactor, simplify gates and gate rendering
- [x] Portable gates (with Buildcraft support in mind), there will be a socket, a soldering tool and only one item per gate.
- [ ] Make circuits save per world so that they don't waste space for every single item
- [x] More tooltips and a way to disable them

**Comment by MFernflower** [comment]
Will there be an option for standard 2 input-1 output gates?

**Comment by Victorious3** [comment]
You mean an option to disable interaction on one side? Like a fourth mode? I'm considering something like that but it is more work than you might think.

**Comment by MFernflower** [comment]
I'm not certain what you mean. It's best if I show you a picture - I think 

![fhfhufh](https://cloud.githubusercontent.com/assets/3164942/6929975/3c365aa2-d7cd-11e4-8406-0b86efff5393.png)

**Comment by MFernflower** [comment]
(Sorry its so big)

**Comment by Victorious3** [comment]
You can ctrl + click on an AND gate to cycle the input modes, this is already possible.

**Comment by MFernflower** [comment]
OK thanks. I'm new to this mod.

**Comment by Victorious3** [comment]
Might want to reschedule the latest open point for 1.0, closing for now.
