### ISSUE TITLE
After updating I am now getting a crash

### ISSUE THREAD

**Issue by crunkazcanbe** [Victorious3/Integrated-Circuits#58]
http://pastebin.com/gSgxnA8c

It is wanting me to install bluepower , but I dont want to as I use project Red

**Comment by Victorious3** [comment]
Should be fixed in this build: https://github.com/Victorious3/Integrated-Circuits/releases/tag/0.8r33 Sorry for the inconvenience, testing a mod with that many dependencies is quite hard...
