### ISSUE TITLE
Crash when clicking CAD with a floppy.

### ISSUE THREAD

**Issue by hjake123** [Victorious3/Integrated-Circuits#59]
I was trying to figure out how to insert the floppy into the CAD (still not sure about that- it blocks your inventory), and I started spam-clicking the side of the two machines (I stacked them, screenshot below), and I earned this: https://docs.google.com/document/d/1W8JGmdpnDIWcJrS4brvh3i8WSYUQpt2RnFgKigm7Jkg/edit?usp=sharing

Since I was moving a bit, it may have been either machine. Sorry for the uncertainty.

EDIT: I reproduced it without a floppy disk in hand. I was on the CAD, for sure, and I was spamming the front face. The second log was identical.

![2015-03-24_18 21 51](https://cloud.githubusercontent.com/assets/5803666/6815038/eb6b4b0c-d252-11e4-9839-cfb80cc9d1b0.png)

**Comment by Victorious3** [comment]
Already had something like this, hard to tackle. I will look into it for the next release. 

Here:
![How To](http://giant.gfycat.com/DimwittedChiefGoldeneye.gif)

**Comment by hjake123** [comment]
Actually, I think spamming that part was what crashed... anyway,  thanks!

**Comment by Victorious3** [comment]
@hjake123 Needs to be verified, check the latest build on the Jenkins: http://jenkins.rx14.co.uk/job/Vic/job/Integrated-Circuits/119/

**Comment by Victorious3** [comment]
Also still open, needs a fix for 0.9
