### ISSUE TITLE
Server crash with IC and ForgeEssentials

### ISSUE THREAD

**Issue by Pyeroh** [Victorious3/Integrated-Circuits#61]
Here's the server log : http://pastebin.com/ms88FhxY

When one or the other is disabled, the server starts correctly, but when they are both enabled, it crashes (without crash log, additionally). I use IC 0.8-r33, CodeChickenCore 1.0.4.35 and FE 1.4.0-beta5. If it's an issue on FE side, I'll notify them.

**Comment by Victorious3** [comment]
Will be in the next release, for now you can use the jenkins build: http://jenkins.rx14.co.uk/job/Vic/job/Integrated-Circuits/109/

**Comment by Pyeroh** [comment]
Thanks a lot ! :D
