### ISSUE TITLE
SMP Crash when using CAD

### ISSUE THREAD

**Issue by maxss** [Victorious3/Integrated-Circuits#62]
When PersonA waches the CAD  (CAD gui opened) and PersonB removes the inserted Floppy the client of PersonA crashes.

CrashLog: http://pastebin.com/tYieVqHu
LoadLog: http://pastebin.com/F8ribhWB

**Comment by Victorious3** [comment]
Couldn't reproduce in 0.9. If it happens again, please re-open.
