### ISSUE TITLE
Crash ;-;

### ISSUE THREAD

**Issue by dahjin** [Victorious3/Integrated-Circuits#65]
pastebin: http://pastebin.com/kBTBqS4h

**Comment by Victorious3** [comment]
Doesn't make much sense as said class is here: https://github.com/Victorious3/Integrated-Circuits/blob/master/src/main/java/dan200/computercraft/api/peripheral/IPeripheralProvider.java
This was built with the API version 1.64, it could be that there was a newer one released in the meantime but I don't think so. I double checked the release version, said class is packaged and available.

**Comment by dahjin** [comment]
im trying to run it with the newest open computers and no computercraft tho unless that's not allowed at all.

**Comment by Victorious3** [comment]
You should be able to run it without CC, as I said, said class is included and should not fail to load. Open the file in some zip editor and make sure that it exists...

**Comment by dahjin** [comment]
yep sorry i dont know much about debugging mods :S

http://i.imgur.com/kNF6oTJ.png

**Comment by Victorious3** [comment]
Doesn't make any sense... Try installing CC and check if it runs, however, I know people who managed to run it without CC installed...

**Comment by dahjin** [comment]
it does.

**Comment by dahjin** [comment]
ill make a clean pack and only use your mod and CC

**Comment by Victorious3** [comment]
Wait, you have CC and it crashes? I use it with 1.65

**Comment by dahjin** [comment]
im sorry i meant if i have CC it runs if i dont it crashes.

**Comment by Victorious3** [comment]
I could fix it by adding a few `@Method` annotations, but this is somewhat weird...

**Comment by dahjin** [comment]
huh seems to actually be something different entirely as it works with OC and just integrated circuits

**Comment by Victorious3** [comment]
Suspicious. Try removing CoFH core, maybe it does some weird ASM that screws everything over. I'll leave this open and going to 'fix' it the next version.

**Comment by dahjin** [comment]
Nah not cofh either so ill just go down the list in my pack untill it crashes and let you know.

**Comment by dahjin** [comment]
the mod seems to be enhanced portals 3.

**Comment by Victorious3** [comment]
You should create an issue on their side here: https://github.com/enhanced-portals/enhanced-portals Again, I'll fix it for the next release but something like this should be impossible in the first place.

**Comment by simlhawk** [comment]
I have the same crash, but no Enhanced Portals. There may be multiple mod incompatibilities.

**Comment by Victorious3** [comment]
Here's a new build, someone please verify: http://jenkins.rx14.co.uk/job/Vic/job/Integrated-Circuits/116/

**Comment by simlhawk** [comment]
No luck: http://pastebin.com/sYLXEvSp
This shouldn't be happening anyways, dan200's API is shipped. I have a feeling its another mod causing this issue, I'll do a bit of snooping around.

**Comment by Victorious3** [comment]
Well, this time its a different one, doesn't even point at any of my classes...

**Comment by Victorious3** [comment]
This is line 123: `blockGate = new BlockGate();`
I don't even import IPeripheral there...

**Comment by Voidi** [comment]
Yes, may be DragonAPI
http://wolkenstein.dertobi.name/~tobias/upload/Minecraft/logs/reika/fml-client-2.log

Key lines
`[21:25:25] [Client thread/INFO] [FML/RotaryCraft]: DRAGONAPI ASM: Injecting 3 interfaces into Reika/DragonAPI/Base/TileEntityBase: [dan200.computercraft.api.peripheral.IPeripheral, li.cil.oc.api.network.Environment, li.cil.oc.api.network.ManagedPeripheral]
[21:25:25] [Client thread/INFO] [FML/RotaryCraft]: DRAGONAPI ASM: Interface class dan200.computercraft.api.peripheral.IPeripheral not found. Injection failed.
[21:25:25] [Client thread/INFO] [FML/RotaryCraft]: DRAGONAPI ASM: Interface class li/cil/oc/api/network/Environment successfully injected.
[21:25:25] [Client thread/INFO] [FML/RotaryCraft]: DRAGONAPI ASM: Interface class li/cil/oc/api/network/ManagedPeripheral successfully injected.
[21:25:25] [Client thread/INFO] [FML/RotaryCraft]: DRAGONAPI ASM: Removing Method: 'Reika/DragonAPI/Base/TileEntityBase.equals(Ldan200/computercraft/api/peripheral/IPeripheral;)Z'; Reason: Required mod COMPUTERCRAFT not loaded.
`

**Comment by Victorious3** [comment]
Closing this as it is getting a major rewrite anyways. I'll try to get away from depending on CC's interfaces.

**Comment by apotheoseGrifter** [comment]
Hey, I know that you're closing this issue and this will probably become a moot point and all, but I spent six and a half hours trying to troubleshoot this before I thought to check the bug reports and what I've observed is so bizarre that I have to share what I found anyway. The best I can guess is that this bug is the result of some sort eldritch abomination summoned by the complex interaction between multiple mods, and requires only these exact following mods (and their prerequisites) to replicate: 

Computronics-1.7.10-.1.5.1
integratedcircuits-1.7.10-0.8r34b
Mekanism-1.7.10-8.1.3.231
NotEnoughItems-1.7.10-1.0.5.110-universal

The crash report with this set of mods is identical to simlhawk's. Curiously, it seems that the exact same error also generates if I put Integrated Circuits and NEI in together without CodeChickenCore, though at least it does crash much faster. I did a quick search and all four of these mods are in every bug report except the first, which lacks Mekanism but seems to be an entirely different error anyway. I am no programmer and have no idea what's going on, but with a bug this complex it's probably for the best that you're rewriting it entirely.

**Comment by Victorious3** [comment]
@apotheoseGrifter 0.8r34b is too old, try the latest build from the Jenkins: http://jenkins.rx14.co.uk/job/Vic/job/Integrated-Circuits/167/ 
Thanks for your effort though, this is one of the weirdest bugs I've ever had...

**Comment by apotheoseGrifter** [comment]
Yep, the new build works perfectly fine with my set-up (which contains all the mods mentioned above). A new problem cropped up, but it was a minor issue and completely unrelated. I'll to send another ticket with it, just for notification's sake.
