### ISSUE TITLE
Port bugfixes to 0.9

### ISSUE THREAD

**Issue by Victorious3** [Victorious3/Integrated-Circuits#71]
Sadly, as of the package rename, I can't simply cherry-pick the commits.

**Comment by Victorious3** [comment]
Everything since d30d0028ae607cd13e518598b23d8fdd85e5cff6 has to be carried over.

**Comment by skyem123** [comment]
Okay, I'll do this when I can actually install java. on. this. netbook. with. slow. internet.

**Comment by skyem123** [comment]
Well... As you did a git rename properly, you CAN do a git cherry pick! ^^
f961bc18cec9bbd3204c77bd964f384ca57feb18 should be it.

**Comment by Victorious3** [comment]
Well, I didn't really try it, but that's nice to know.
