### ISSUE TITLE
java.lang.NoSuchMethodError crash

### ISSUE THREAD

**Issue by halvors** [Victorious3/Integrated-Circuits#76]
Here is the crashlog, i don't really have much more information because i just saw this in the server log. I'm not the one who triggered the crash, some other user on the server was playing around wit Integrateed Circuits. 

http://pastebin.com/wjbP8meM

**Comment by Victorious3** [comment]
And that's downright impossible if called in the normal way because it calls an interface methods which is *likely* implemented. It could be something with OC's ASM derping, I'll have a look at it later.

**Comment by halvors** [comment]
Thanks :+1:

**Comment by Victorious3** [comment]
@halvors can you try the newest build from the jenkins? (http://jenkins.rx14.co.uk/job/Vic/job/Integrated-Circuits/126/) It seems to happen when you destroy a gate, maybe attached to an OC computer, so please try if that works now.

**Comment by halvors** [comment]
@Victorious3 I'm sorry, but i'm not able to test this until there is a stable version of forge with the fluid api changes out. Because this change to 1355+ is going to break my other mods.

**Comment by Forecaster** [comment]
The above build works!

**Comment by skyem123** [comment]
@Victorious3, this issue seems to be gone now, and I have a feeling that I've also fixed an issue similar to this one, so can this be closed?
