### ISSUE TITLE
Request: RedLogic bundled cable support

### ISSUE THREAD

**Issue by Techokami** [Victorious3/Integrated-Circuits#8]
Pretty much what it says on the box. I'm very thankful that P:R is now optional, because I'm using RedLogic on my server. But I like the direction this mod is going in, compared to the integrated circuits system in RedLogic. Only thing that is missing for me then, is bundled cable support.

Maybe this could also be expanded with MineFactoryReloaded RedNet support, too? That way, you can use the wave generators in MFR to drive an IC...

**Comment by Victorious3** [comment]
Now implemented via b88db9c, just need some more testing before the next build.

**Comment by Techokami** [comment]
Oh my god thank you so much
