### ISSUE TITLE
Load 0.8 circuits in 0.9

### ISSUE THREAD

**Issue by skyem123** [Victorious3/Integrated-Circuits#88]
It would probably be a good idea if circuits placed in 0.8 are converted when people upgrade to 0.9

**Comment by evg-zhabotinsky** [comment]
As far as I understand, @Victorious3 has no plans on placed IC conversion.
Non-fmp IC items, however, already "convert" to 0.9 properly (they are the same item).
Converting FMP CI items will require using a dummy item (as converting placed ICs will require dummy TEs).

Anyway, adding these dummy items and TEs for at least one mod version might be a good idea.

**Comment by skyem123** [comment]
@Victorious3, what do you think about this?
Is it too late?

**Comment by ljfa-ag** [comment]
This has already been added wasn't it?

**Comment by evg-zhabotinsky** [comment]
Dummy items / TEs are not implemented, so all placed ICs and FMP IC items will disappear on first load (forge warns about it).
Floppies and non-FMP IC items should be fine, and most circuits (even tick-tight) should work as before (except those relying on old incorrect behavior of some gates).

**Comment by skyem123** [comment]
Would it be a good idea if placed circuits were automatically converted?

**Comment by evg-zhabotinsky** [comment]
If you assume that everybody keeps all their IC designs on floppies, it should not really matter, except for huge creative designs maybe. But something tells me that this assumption is not correct.

**Comment by skyem123** [comment]
Hmm... I'm just thinking of the possible inconvienience this could cause...
Ah well...

Date: Fri, 14 Aug 2015 15:04:21 -0700

**Comment by evg-zhabotinsky** [comment]
Personally, I think that dummy TEs and items should be implemented, and then they can be dropped after a few versions. But I have no idea how to do it properly.

**Comment by skyem123** [comment]
Well... learning how to do them will be useful for the upgrade from 0.9 to 1.0...
@Victorious3, so... how do you make dummy tile entities?

**Comment by Victorious3** [comment]
@skyem123 At best... Not at all. I don't plan to change this again, and legacy code is evil.

**Comment by skyem123** [comment]
D:

**Comment by evg-zhabotinsky** [comment]
It will not be legacy code. It will be a (code-wise separate) built-in 0.8->0.9 save converter that will be dropped a bit later (or not dropped, as it will only consume 1 item ID and 1 block ID). Otherwise I agree that writing something that will not be needed later is far from being an appealing task. I am not sure if this specific task is really important.

**Comment by skyem123** [comment]
@Victorious3, as we are in 0.9, does that mean that I should close this?
