### ISSUE TITLE
Get rid of ADCs/DACs on I/O

### ISSUE THREAD

**Issue by SoniEx2** [Victorious3/Integrated-Circuits#9]
ADCs and DACs are bad and you should be able to select if you want them or not. Also IRL circuits can do raw analog (without ADCs/DACs everywhere) so it'd make more sense to not have them there.

**Comment by Victorious3** [comment]
Changing the internals to analog would mean 
1) rewriting a whole bunch of the IO, 
2) rewriting my entire data structure because right now each circuit fits into a 32x int nicely. 
3) break compatibility with older versions
So no, not going to happen, I'm sorry.

**Comment by SoniEx2** [comment]
why (3)?

**Comment by Victorious3** [comment]
It works like metadata one could say, every circuits is a 2D array of integers, using analog would need 16 bits instead of 4 for digital.
