### ISSUE TITLE
Failed injecting component logic

### ISSUE THREAD

**Issue by Tsyklop** [Victorious3/Integrated-Circuits#97]
I install Integrated-Circuits 0.9r34.151 and install OpenComputers 1.5.12.26, And when I go into the world shows me here is:
![2015-05-29_07 42 14](https://cloud.githubusercontent.com/assets/6783568/7876618/53340398-05d7-11e5-99ff-dedcb5d715b1.png)

A log file error: http://pastebin.com/hyddxnNb

**Comment by Victorious3** [comment]
Don't try to use 0.9, it's not ready yet. Thanks for the report though, I'll have a look.

**Comment by Tsyklop** [comment]
@Victorious3 The latest version 0.8 requires ComputerCraft. I do not have it in the assembly and will not put. Without it, the client crash!

**Comment by skyem123** [comment]
So 0.8 crashes the whole client when ComputerCraft is not installed and OpenComputers is installed?

**Comment by Tsyklop** [comment]
@skyem123 yes

**Comment by skyem123** [comment]
Can you open a new issue for that and  link the crashlog in a pastebin there?

**Comment by Tsyklop** [comment]
@skyem123 here https://github.com/Victorious3/Integrated-Circuits/issues/77 -  same error.

**Comment by skyem123** [comment]
Well, there's not much I can do about this, so we'll have to wait for @Victorious3.

**Comment by Tsyklop** [comment]
@skyem123 pastebin does not allow to put all the crash report. Where can I fill in the entire crash report or where you can fill in the file?

**Comment by skyem123** [comment]
GitHub gist?

**Comment by Tsyklop** [comment]
@skyem123 https://gist.github.com/Tsyklop/af78fa8f313cd5b17c6f

**Comment by skyem123** [comment]
Is that crashlog for the 0.8 crash?

**Comment by Tsyklop** [comment]
@skyem123 yes (integratedcircuits{1.7.10-0.8r34b})

**Comment by Victorious3** [comment]
Yeah and its the same one, no clue. Sometimes it happens, sometimes it doesn't.
@Tsyklop The interface is injected to the TE later on, it might not recognize it anymore, have you tried? I'll see if I can get rid of that error message somehow, but I need the interface on there.

**Comment by Tsyklop** [comment]
@Victorious3 TE - ThermalExpansion? I do not understand. What should I try?

**Comment by skyem123** [comment]
"TE" means "tile entity" in this case.

**Comment by Tsyklop** [comment]
I got it. But I entirely 'still do not understand that I had to try it?

**Comment by Victorious3** [comment]
@Tsyklop Ignore it and try if it works anyways.

**Comment by Tsyklop** [comment]
@Victorious3 whether integration with OpenComputers?

**Comment by Victorious3** [comment]
Indeed, try to put a circuit next to a computer.

**Comment by Tsyklop** [comment]
No errors, no crashe`s

**Comment by Victorious3** [comment]
Yeah, but the question is, does it work? Try using it.

**Comment by Tsyklop** [comment]
work

**Comment by Victorious3** [comment]
@Tsyklop I'm trying to find a way around this right now.
