### ISSUE TITLE
Can not change mode for XOR and XNOR gates

### ISSUE THREAD

**Issue by Surrogard** [Victorious3/Integrated-Circuits#99]
Hi,

the inputs of the XOR and XNOR gates can not be toggled with the Edit tool in CAD view.
Is this by design (which I don't think)?

Best Regards

p.s.: I'm using the newest version from Jenkins: 1.7.10-0.9r34.167

**Comment by Victorious3** [comment]
That's intended, yes. Is there a need for it? They only have two inputs.

**Comment by skyem123** [comment]
Technically, an XOR gate can have more than 2 inputs...

**Comment by Surrogard** [comment]
But more importantly for me is rearranging the inputs for a more compact
schematic

Skye <notifications@github.com> schrieb am Do., 4. Juni 2015 23:54:

**Comment by ljfa-ag** [comment]
XOR with three inputs might be ambiguous. There are multiple ways how the truth table for that could look like, e.g. "exactly one input is high" or "an odd number of inputs is high".

**Comment by Victorious3** [comment]
@ljfa-ag yep.
I was doing this after the P:R scheme which doesn't allow you to change the inputs of those types, but I guess moving them to another side can be useful.
@Surrogard I'll see if I can get this into 0.9 before release

**Comment by Surrogard** [comment]
Many thanks Vic.
And regardless of this feature: great mod!

Vic Nightfall <notifications@github.com> schrieb am Fr., 5. Juni 2015 00:10:

**Comment by evg-zhabotinsky** [comment]
In my pull request I allowed to move inputs to other sides, but not to use 3 inputs.

Also:

I don't think that 3-input XOR is ambiguous.
Kind of `a XOR (b XOR c) == (a XOR b) XOR c == a XOR b XOR c == XOR(a, b, c)`

But XOR implementation in hardware is more complex than that of AND or OR for example, and 3-input version would be twice as complex, while 3-input OR and AND gates are just half more complex than 2-input versions (1 transistor per input, in general).

**Comment by evg-zhabotinsky** [comment]
This is fixed by #113 probably should be closed.
